### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by max-frai** [rendinjast/iconsax-react#1]
Hello! I found your publication on reddit and decided to try it. My config is latest expo build and I found that single import into minimal working example of icon from your package adds 1gb ram usage to the application. Without it it's 80 mb.

```
import {StatusBar} from "expo-status-bar";
import React from "react";
import {StyleSheet, Text, View} from "react-native";

import {EmojiHappy} from "iconsax-react-native"; // Without this line ram usage is 80mb

export default function App() {
    return (
        <View style={styles.container}>
            <Text>Open up App.js to start working on your app!</Text>
            <StatusBar style="auto" />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
        alignItems: "center",
        justifyContent: "center",
    },
});

```
![photo_2021-10-30 01 50 23](https://user-images.githubusercontent.com/24208746/139509316-479c32da-c271-4e28-9e27-b5cd15039529.jpeg)

**Comment by rendinjast** [comment]
Hi.
I think Its because expo compile whole liberary which is 11M and 1000 icon!
In production you won't have this problem.

**Comment by max-frai** [comment]
Okay, thank you.
