### ISSUE TITLE
Wrong icons

### ISSUE THREAD

**Issue by tuphan-dn** [rendinjast/iconsax-react#4]
I think the `Wallet` and `Wallet1` in the `Outline` variant have been unintendedly swapped to each other.

**Comment by tofful** [comment]
@tuphan-dn I have seen that a lot of icons presents the same issue, such as the `Star` icon.

**Comment by rendinjast** [comment]
hi. 
a lot of icons had same issue which came from original project and I fixed many of them but still there are some icon with wrong name.

**Comment by rendinjast** [comment]
version 0.0.7 => `Wallet`,`Wallet1` and `Star`,`Star1` name fixed
