### ISSUE TITLE
Production bundle returns all 6000 icons even when I import only 1 icon 

### ISSUE THREAD

**Issue by tofful** [rendinjast/iconsax-react#5]
As a dev, I would like to use iconsax library and I would like to use some of the icons, in my case, only one icon:

```
import { Folder } from 'iconsax-react';

...
return <Folder className={styles.icon} color={iconColor} variant="Bulk" aria-hidden />;
...

```

when I look at the generated bundle I expect to see one icon with the variant Bulk being generated, but instead, I see that all 6000 icons are included. This brings a lot of performance issues.

Looking at the Chrome DevTools I can see that the icons chunk takes 16 seconds to load when it is not in cache.

![image](https://user-images.githubusercontent.com/1058850/143153069-9d7d4fae-ae90-4167-bde8-6bf78ffcb951.png)

**Solution**
To include in the bundle only the icons used. Maybe the `import` should be something like this

```
import Folder from 'iconsax-react/Folder';
```

This way, we could even use it as lazy, please have a look at my simplified code:

```

import React, { Suspense, lazy } from 'react';

const Folder = lazy(() => import('iconsax-react/Folder')); <--- Lazy import

...
return (
    <Suspense fallback={null}>
        <Folder className={styles.icon} color={iconColor} variant="Bulk" aria-hidden />
    </Suspense>;
)
...

```

**Comment by tofful** [comment]
@rendinjast what do you think?

**Comment by max-frai** [comment]
@tofful I have same problem in react native. I think there is some problem with generation of modules. But didn't have time to look what's wrong.

**Comment by rendinjast** [comment]
I'm aware of this issue but unfortunately I did not have access to my computer this month to working on it.
-------


> @rendinjast what do you think?

that's good idea.I might do that.

**Comment by rendinjast** [comment]
fixed this issue.
version 0.0.4:

![004](https://user-images.githubusercontent.com/63567298/143367144-1cd864c0-ab7e-4ff1-baa5-5e9b1ca5f4c0.png)

version 0.0.6:
![006](https://user-images.githubusercontent.com/63567298/143367205-29153813-0747-4fa9-a5c4-84efd4093f47.png)

please check new version and let me know if there is any issue.

**Comment by tofful** [comment]
wow great one @rendinjast thanks for pushing up the changes, it didn't address the issue as all icons are still being included in the bundle but at least I can see now a very significant file size reduction which is fantastic. Thank you very much for the prompt reply

**Comment by erfanasbari** [comment]
@rendinjast it would be great if you could add the ability to import every icon individually.

like this: `import  Hashtag  from "iconsax-react/Hashtag";`

This will help reducing compile time in dev environment in frameworks like Nextjs

I tested iconsax-react and it adds 2 seconds to compile time (In my environment). if i could import every icon individually compile time would be reduced.

react-icons done this because of their huge amount of icons: https://www.npmjs.com/package/@react-icons/all-files

**Comment by erfanasbari** [comment]
And large bundle size problem has been fixed.

Thanks!!!

**Comment by erfanasbari** [comment]
It looks like i can import icons individually but I get typescript error.

`import { CloudSunny } from "iconsax-react/dist/cjs/CloudSunny";`

**Comment by rendinjast** [comment]
> It looks like i can import icons individually in version 0.0.6 but I get typescript error.
> 
> `import { CloudSunny } from "iconsax-react/dist/cjs/CloudSunny";`

Yes you can.
Can i see the typescript error?
Did you try to import from esm?
```js
import { CloudSunny } from "iconsax-react/dist/esm/CloudSunny";
```

**Comment by tofful** [comment]
@rendinjast  this is the typescript error I get when I try to import the icon as your recommendation.

![image](https://user-images.githubusercontent.com/1058850/143507636-411809a5-1037-4480-9a2d-f785f271badc.png)

**Comment by tofful** [comment]
@rendinjast this is the Typescript error that I got when I tried your recommended import syntax

![image](https://user-images.githubusercontent.com/1058850/143507809-c14919d8-733d-4f7b-91cd-b63380d5f3c1.png)

**Comment by rendinjast** [comment]
@tofful oh. its because when you import icon this way there is no type for that.

create a `.d.ts` file that contains 
```ts
declare module 'iconsax-react/dist/esm/*';
```

**Comment by tofful** [comment]
great @rendinjast  thank you so much, I guess from my side I will just add a `// @ts-ignore` to the `import` because I believe maybe the type declaration could come as part of the library.

A last question from my side and then I believe we can safely close this issue.


Is it too much hassle to do a `default` export of the icons? like `export default CloudSunny` and elseo `export { CloudSunny }`
this is because it would be great to import icons as `lazy` 

`import CloudSunny from "iconsax-react/dist/esm/CloudSunny";`

instead of just being able to import only via:

`import { CloudSunny } from "iconsax-react/dist/esm/CloudSunny";`



![image](https://user-images.githubusercontent.com/1058850/143509120-ac28d9a9-dfd6-4c35-8460-8fa059b2e049.png)

**Comment by tofful** [comment]
New error found when running React test suit, it seems that it doesn't recognize the `import`

Please have a look at my screenshot

![image](https://user-images.githubusercontent.com/1058850/143523620-4122799a-9f20-4322-b3ff-e57b80094502.png)

**Comment by rendinjast** [comment]
@tofful version 0.0.7. now you can import default icons. like:

`import CloudSunny from "iconsax-react/dist/esm/CloudSunny";`

-----------
the error is because you are using ECMAScript module.

**Comment by tofful** [comment]
@rendinjast  fantastic!! you rock! everything is working as expected

**Comment by tofful** [comment]
with version `v0.0.7`  in place, all the defects on this issue have been addressed, therefore is it safe to close this issue and mark it as done.
